name: AI Agent Tests

on:
  pull_request_target:
    branches: [ main ]

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ai-testing
    
    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        # Test code in the PR, not main
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Validate ANTHROPIC_API_KEY secret
      run: |
        if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
          echo "Error: ANTHROPIC_API_KEY secret is not set or is empty"
          echo "Configure the ANTHROPIC_API_KEY secret in the 'ai-testing' environment"
          echo "Go to: Repository Settings → Environments → ai-testing → Environment secrets"
          exit 1
        else
          echo "ANTHROPIC_API_KEY secret is configured correctly"
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Claude Code CLI
      run: |
        npm install -g @anthropic-ai/claude-code
        
        # Verify installation
        claude --version

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install pyyaml jsonschema
    
    - name: Run AI agent tests
      run: |
        # Run the tests
        ./test.sh
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
